services:

  db:
    image: postgres

    environment:
      POSTGRES_DB: syncboard
      POSTGRES_USER: syncboard
      POSTGRES_PASSWORD: syncboard

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syncboard -d syncboard"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: