export const ErrorCode = {
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    RESOURCE_ALREADY_EXIST: "RESOURCE_ALREADY_EXIST",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    VALIDATION_FAILED: "VALIDATION_FAILED",
    ACCESS_DENIED: "ACCESS_DENIED",
    UNAUTHORIZED: "UNAUTHORIZED",
    BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];